export const runtime = 'nodejs'

import { requirePermission } from '@/lib/permissions'
import { ok, badRequest, serverError } from '@/lib/api-response'
import { z } from 'zod'

const bodySchema = z.object({
  productName: z.string().min(1),
  brand: z.string().optional(),
  fabric: z.string().optional(),
  keyFeatures: z.array(z.string()).default([]),
  occasions: z.array(z.string()).default([]),
  careInstructions: z.array(z.string()).default([]),
  imageUrls: z.array(z.string().url()).default([]),
  style: z.enum(['luxury', 'casual', 'minimal', 'detailed']).default('detailed'),
})

// ── Google Gemini AI Description Generator ──
// Uses Gemini 1.5 Flash (free tier) to generate enterprise-level product descriptions.
// Falls back to local template generator if GEMINI_API_KEY is not set or API fails.

async function generateWithGemini(data: z.infer<typeof bodySchema>): Promise<string | null> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) return null

  const imageSection = data.imageUrls.length > 0
    ? `\n\nThe product has ${data.imageUrls.length} image(s). Use these URLs in the HTML:\n- Hero banner (first image): ${data.imageUrls[0]}\n${data.imageUrls.slice(1).map((url, i) => `- Gallery/detail image ${i + 2}: ${url}`).join('\n')}`
    : ''

  const prompt = `You are a world-class e-commerce product description writer and HTML/CSS designer.

Generate a COMPLETE, self-contained HTML product description page for the following product. The output must be production-ready HTML that looks stunning on both mobile and desktop.

**Product Details:**
- Name: ${data.productName}
${data.brand ? `- Brand: ${data.brand}` : ''}
${data.fabric ? `- Fabric/Material: ${data.fabric}` : ''}
${data.keyFeatures.length > 0 ? `- Key Features: ${data.keyFeatures.join(', ')}` : ''}
${data.occasions.length > 0 ? `- Occasions: ${data.occasions.join(', ')}` : ''}
${data.careInstructions.length > 0 ? `- Care Instructions: ${data.careInstructions.join(', ')}` : ''}
- Writing Style: ${data.style}${imageSection}

**STRICT Requirements:**
1. Output ONLY raw HTML — no markdown, no code fences, no explanation
2. Start with a <style> tag containing ALL CSS (self-contained, no external CSS imports except Google Fonts)
3. Use Google Fonts "Inter" with weights 400,500,600,700,800
4. Wrap everything in <article class="pd-desc">
5. Use these CSS class prefixes: pd-hero, pd-intro, pd-gallery, pd-fabric, pd-features, pd-occasions, pd-quality, pd-care, pd-closing
6. Include a hero banner section with the first image (full-width, rounded, max-height 480px, object-fit cover)
7. Include an image gallery grid if multiple images exist (responsive grid, rounded corners)
8. Include mid-section and lifestyle images between content sections
9. Feature list should use checkmark badges (purple circles with white checkmarks)
10. Occasion tags should be pill-shaped with gradient backgrounds
11. Care instructions in a 2-column grid (1 column on mobile)
12. Closing section with gradient background and CTA text
13. ALL images must use loading="lazy" except the hero
14. Responsive: use clamp() for font sizes, adjust padding/layout at max-width 480px
15. Color scheme: headings #2d2d4e, body #555, accent #7c3aed, light bg #f8f7ff
16. Max-width 760px centered, clean typography, generous whitespace
17. Make it look like a premium Shopify product page
18. Write compelling, original, non-copyrighted marketing copy
19. The description should be 400-600 words of actual content
20. Do NOT include <html>, <head>, or <body> tags — just <style> + <article>`

  const MODELS = ['gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-1.5-flash-8b']
  const payload = JSON.stringify({
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.8, maxOutputTokens: 4096, topP: 0.95 },
  })

  for (const model of MODELS) {
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
        { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: payload }
      )

      if (res.status === 429) {
        console.warn(`Gemini ${model} rate-limited, trying next model…`)
        await new Promise(r => setTimeout(r, 1200))
        continue
      }

      if (!res.ok) {
        const errText = await res.text().catch(() => '')
        console.error(`Gemini ${model} error ${res.status}:`, errText)
        continue
      }

      const json = await res.json()
      const text = json?.candidates?.[0]?.content?.parts?.[0]?.text
      if (!text) { console.warn(`Gemini ${model} returned empty text`); continue }

      let html = text.trim()
      if (html.startsWith('```html')) html = html.slice(7)
      else if (html.startsWith('```')) html = html.slice(3)
      if (html.endsWith('```')) html = html.slice(0, -3)
      console.log(`Gemini description generated by ${model}`)
      return html.trim()
    } catch (err) {
      console.error(`Gemini ${model} call failed:`, err)
    }
  }

  console.warn('All Gemini models failed — using local fallback')
  return null
}

// ── Fallback: Local template-based generator ──
// Used when GEMINI_API_KEY is not set or Gemini fails

function generateDescription(data: z.infer<typeof bodySchema>): string {
  const name = esc(data.productName)
  const brand = data.brand ? esc(data.brand) : ''
  const fabric = data.fabric ? esc(data.fabric) : ''
  const features = data.keyFeatures.map(esc)
  const occasions = data.occasions.map(esc)
  const care = data.careInstructions.map(esc)
  const images = data.imageUrls || []
  const isLuxury = data.style === 'luxury'
  const isMinimal = data.style === 'minimal'

  // Pick helper for randomized content
  const pick = <T,>(pool: T[], count: number): T[] => {
    const shuffled = [...pool].sort(() => Math.random() - 0.5)
    return shuffled.slice(0, Math.min(count, pool.length))
  }

  // ── Hero Banner ──
  const heroBanner = images.length > 0
    ? `<div class="pd-hero">
    <img src="${images[0]}" alt="${name}" class="pd-hero__img" />
  </div>` : ''

  // ── Image Gallery ──
  const galleryHtml = images.length > 1
    ? `<section class="pd-gallery">
    <div class="pd-gallery__grid">
${images.slice(1, 5).map((url, i) => `      <img src="${url}" alt="${name} - View ${i + 2}" class="pd-gallery__item" loading="lazy" />`).join('\n')}
    </div>
  </section>` : ''

  // ── Mid-section image ──
  const midImage = images.length > 2
    ? `<div class="pd-mid-image">
    <img src="${images[Math.min(2, images.length - 1)]}" alt="${name} - Detail" loading="lazy" />
  </div>` : ''

  // ── Lifestyle image ──
  const lifestyleImage = images.length > 3
    ? `<div class="pd-lifestyle-img">
    <img src="${images[3]}" alt="${name} - Lifestyle" loading="lazy" />
  </div>` : ''

  // ── Intro paragraphs ──
  const introPool = [
    `Discover the ${name} — where thoughtful design meets everyday elegance.`,
    `The ${name} is crafted for those who believe great style should never be complicated.`,
    `Introducing ${name}: a piece that effortlessly combines form, function, and flair.`,
    `Meet your new wardrobe essential. The ${name} was designed to make a lasting impression.`,
    brand ? `From the ateliers of ${brand} comes the ${name} — a testament to refined taste and modern craft.` : `Every element of the ${name} has been considered with care, resulting in a piece that truly stands apart.`,
    `There are garments you wear, and then there are garments that wear well. The ${name} belongs firmly in the latter category.`,
    `Style meets substance in the ${name}. A design born from passion, refined through precision.`,
    `The ${name} represents a new standard in contemporary fashion — where luxury is accessible and quality is non-negotiable.`,
  ]

  // ── Fabric paragraphs ──
  const fabricPool = fabric ? [
    `Crafted from premium ${fabric}, the hand-feel is immediately noticeable — soft, substantial, and reassuringly high-quality.`,
    `The ${fabric} construction provides a natural drape and breathability that keeps you comfortable from morning to evening.`,
    `We selected ${fabric} for its balance of durability and luxury. It washes well, wears better, and ages beautifully.`,
    `The fabric story begins with ${fabric} — chosen not just for how it looks, but for how it makes you feel.`,
    `Premium ${fabric} undergoes rigorous quality checks at every stage, ensuring only the finest reaches your wardrobe.`,
  ] : [
    `Premium materials were carefully sourced to deliver comfort without compromise.`,
    `The fabric has been selected for its exceptional hand-feel, breathability, and lasting quality.`,
    `Every thread contributes to a garment that maintains its shape, softness, and color integrity over time.`,
    `Sourced from trusted suppliers who share our commitment to quality and ethical production practices.`,
  ]

  // ── Feature sentences ──
  const featureSentences = features.length > 0
    ? features.map((f, i) => {
      const templates = [
        `<strong>${f}</strong> — a detail that elevates the entire design.`,
        `<strong>${f}</strong> adds both visual interest and practical value.`,
        `The inclusion of <strong>${f}</strong> speaks to the level of thought behind every decision.`,
        `<strong>${f}</strong> — because exceptional products deserve exceptional details.`,
      ]
      return templates[i % templates.length]
    })
    : []

  // ── Occasion sentences ──
  const occasionPool = occasions.length > 0
    ? [
      `Style it for ${occasions.join(', ').replace(/, ([^,]*)$/, ' or $1')} — it adapts beautifully to every setting.`,
      `Whether you are dressing for ${occasions[0]?.toLowerCase() || 'a special event'} or keeping things relaxed, this piece transitions with ease.`,
      `The versatility of the ${name} means it moves seamlessly between ${occasions.slice(0, 2).join(' and ').toLowerCase() || 'different'} contexts.`,
      `From ${occasions[0]?.toLowerCase() || 'formal'} occasions to everyday moments, this piece is your perfect companion.`,
    ]
    : [
      `Designed for real life: the kind of piece that works whether you are running errands or meeting friends.`,
      `Its versatile character means endless styling possibilities — dress it up, dress it down, make it yours.`,
      `Equally at home in professional settings as it is during leisure time — a truly indispensable wardrobe staple.`,
    ]

  // ── Quality sentences ──
  const qualityPool = [
    `Every seam is reinforced at stress points for longevity that matches the investment.`,
    `Color-fast dyes ensure vibrancy that lasts wash after wash — no fading, no surprises.`,
    `Hardware and finishing touches are selected for both aesthetics and durability.`,
    `The construction reflects a commitment to quality that you can see, feel, and trust.`,
    `Each piece goes through a final quality inspection before being carefully packaged for delivery.`,
    isLuxury ? `This is the kind of piece that people notice — and remember.` : `Built to be a reliable companion in your daily wardrobe rotation.`,
  ]

  // ── Closing ──
  const closingPool = [
    `Add the ${name} to your collection and feel the difference that intentional design makes.`,
    `This is more than a purchase — it is an upgrade to how you present yourself to the world.`,
    `Limited availability. When it is gone, it is gone. Make it yours today.`,
    brand ? `Experience the ${brand} standard of quality and design with the ${name}.` : `Quality this considered does not come around often. Elevate your wardrobe now.`,
  ]

  // Select content based on style
  const intros = pick(introPool, isMinimal ? 2 : 4)
  const fabrics = pick(fabricPool, isMinimal ? 1 : 3)
  const occasionSentences = pick(occasionPool, isMinimal ? 1 : 3)
  const quality = pick(qualityPool, isMinimal ? 2 : 4)
  const closing = pick(closingPool, 2)

  // ── Build sections ──
  const featureHtml = featureSentences.length > 0
    ? `<section class="pd-features">
    <h2>What Makes It Special</h2>
    <ul class="pd-feature-list">
${featureSentences.map(f => `      <li>${f}</li>`).join('\n')}
    </ul>
  </section>` : ''

  const careHtml = care.length > 0
    ? `<section class="pd-care">
    <h2>Care Guide</h2>
    <ul class="pd-care-list">
${care.map(c => `      <li>${c}</li>`).join('\n')}
    </ul>
    <p>With proper care, this piece will remain a favourite for years to come.</p>
  </section>` : ''

  const occasionTags = occasions.length > 0
    ? `<div class="pd-tags">${occasions.map(o => `<span class="pd-tag">${o}</span>`).join('')}</div>` : ''

  // ── Inline CSS for self-contained rendering ──
  const css = `<style>
  .pd-desc{font-family:'Inter',system-ui,-apple-system,sans-serif;color:#1a1a2e;max-width:760px;margin:0 auto;padding:0;line-height:1.75;font-size:15px;-webkit-font-smoothing:antialiased}
  .pd-hero{margin-bottom:32px;border-radius:16px;overflow:hidden}
  .pd-hero__img{width:100%;height:auto;max-height:480px;object-fit:cover;display:block}
  .pd-intro{margin-bottom:36px;padding:0 24px}
  .pd-intro h1{font-size:clamp(1.6rem,4vw,2.4rem);font-weight:800;letter-spacing:-0.03em;line-height:1.2;margin:0 0 16px;background:linear-gradient(135deg,#1a1a2e 0%,#4a3a6b 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
  .pd-intro p,.pd-fabric p,.pd-features p,.pd-occasions p,.pd-quality p,.pd-care p,.pd-closing p{font-size:0.92rem;color:#555;margin:0 0 12px;line-height:1.7}
  .pd-fabric,.pd-features,.pd-occasions,.pd-quality,.pd-care,.pd-closing{margin-top:32px;padding:28px 24px 0;border-top:1px solid #eee}
  .pd-fabric h2,.pd-features h2,.pd-occasions h2,.pd-quality h2,.pd-care h2,.pd-closing h2{font-size:clamp(1.1rem,2.5vw,1.35rem);font-weight:700;margin:0 0 14px;color:#2d2d4e;letter-spacing:-0.01em}
  .pd-feature-list{list-style:none;padding:0;margin:16px 0;display:grid;grid-template-columns:1fr;gap:10px}
  .pd-feature-list li{display:flex;align-items:flex-start;gap:10px;padding:14px 18px;border-radius:12px;background:#f8f7ff;font-size:0.88rem;color:#333;border:1px solid #ede9fe}
  .pd-feature-list li::before{content:'\\2713';flex-shrink:0;width:22px;height:22px;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#7c3aed;color:white;font-size:11px;font-weight:700}
  .pd-feature-list li strong{font-weight:600}
  .pd-gallery{margin:32px 0;padding:0 24px}
  .pd-gallery__grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px}
  .pd-gallery__item{width:100%;height:200px;object-fit:cover;border-radius:12px;transition:transform 0.2s}
  .pd-gallery__item:hover{transform:scale(1.02)}
  .pd-mid-image,.pd-lifestyle-img{margin:28px 24px;border-radius:14px;overflow:hidden}
  .pd-mid-image img,.pd-lifestyle-img img{width:100%;height:auto;max-height:360px;object-fit:cover;display:block}
  .pd-tags{margin-top:14px;display:flex;flex-wrap:wrap;gap:8px}
  .pd-tag{display:inline-block;padding:6px 16px;border-radius:99px;background:linear-gradient(135deg,#f0e6ff 0%,#e8f4f8 100%);color:#6b21a8;font-size:0.78rem;font-weight:600;border:1px solid #e2d6f5}
  .pd-care-list{list-style:none;padding:0;margin:12px 0;display:grid;grid-template-columns:1fr 1fr;gap:8px}
  .pd-care-list li{padding:10px 14px;border-radius:10px;background:#fafafa;font-size:0.82rem;color:#555;border:1px solid #eee}
  .pd-care-list li::before{content:'\\2022 ';color:#7c3aed;font-weight:700}
  .pd-closing{text-align:center;padding:32px 24px;background:linear-gradient(180deg,#faf8ff 0%,#f3eeff 100%);border-radius:16px;margin-top:36px;border-top:none}
  .pd-closing h2{color:#4a3a6b}
  .pd-closing p{color:#666}
  @media(max-width:480px){.pd-desc{font-size:14px}.pd-intro{padding:0 16px}.pd-intro h1{font-size:1.5rem}.pd-fabric,.pd-features,.pd-occasions,.pd-quality,.pd-care,.pd-closing{padding:24px 16px 0}.pd-gallery{padding:0 16px}.pd-gallery__grid{grid-template-columns:1fr 1fr}.pd-gallery__item{height:140px}.pd-mid-image,.pd-lifestyle-img{margin:20px 16px}.pd-care-list{grid-template-columns:1fr}.pd-closing{padding:24px 16px}.pd-hero__img{max-height:280px}}
</style>`

  return `${css}
<article class="pd-desc">
  ${heroBanner}

  <section class="pd-intro">
    <h1>${name}</h1>
${intros.map(s => `    <p>${s}</p>`).join('\n')}
  </section>

  ${galleryHtml}

  <section class="pd-fabric">
    <h2>Material &amp; Craft</h2>
${fabrics.map(s => `    <p>${s}</p>`).join('\n')}
  </section>

  ${midImage}

  ${featureHtml}

  <section class="pd-occasions">
    <h2>Wear It Your Way</h2>
${occasionSentences.map(s => `    <p>${s}</p>`).join('\n')}
    ${occasionTags}
  </section>

  ${lifestyleImage}

  <section class="pd-quality">
    <h2>Built to Last</h2>
${quality.map(s => `    <p>${s}</p>`).join('\n')}
  </section>

  ${careHtml}

  <section class="pd-closing">
    <h2>Make It Yours</h2>
${closing.map(s => `    <p>${s}</p>`).join('\n')}
  </section>
</article>`
}

function esc(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export async function POST(request: Request) {
  const { error } = await requirePermission(request, 'products.edit')
  if (error) return error

  try {
    const body = await request.json()
    const parsed = bodySchema.safeParse(body)
    if (!parsed.success) return badRequest('Invalid input', parsed.error.flatten())

    // Try Gemini AI first, fall back to local template
    let html: string | null = null
    let engine = 'local'

    html = await generateWithGemini(parsed.data)
    if (html) {
      engine = 'gemini'
    } else {
      html = generateDescription(parsed.data)
      engine = process.env.GEMINI_API_KEY ? 'local-fallback' : 'local'
    }

    return ok({ html, style: parsed.data.style, engine })
  } catch (err) {
    console.error('AI description error:', err)
    return serverError()
  }
}
